"""Seed dataset definitions for users, amenities, listings, images, reviews, bookings, and favorites."""

from datetime import date, timedelta

USERS_DATA = [
    # 3 Hosts
    {
        "name": "Elena Rostova",
        "email": "elena.rostova@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "role": "host",
    },
    {
        "name": "Marcus Chen",
        "email": "marcus.chen@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
        "role": "host",
    },
    {
        "name": "Sophie Dubois",
        "email": "sophie.dubois@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        "role": "host",
    },
    # 3 Guests
    {
        "name": "Alex Morgan",
        "email": "alex.morgan@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
        "role": "guest",
    },
    {
        "name": "Liam O'Connor",
        "email": "liam.oconnor@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
        "role": "guest",
    },
    {
        "name": "Maya Patel",
        "email": "maya.patel@airbnb-clone.local",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "role": "guest",
    },
]

AMENITIES_DATA = [
    {"name": "Fast Wifi", "icon": "wifi"},
    {"name": "Private Pool", "icon": "waves"},
    {"name": "Hot Tub", "icon": "bath"},
    {"name": "Free Parking", "icon": "square-parking"},
    {"name": "Air Conditioning", "icon": "wind"},
    {"name": "Dedicated Workspace", "icon": "laptop"},
    {"name": "Chef Kitchen", "icon": "utensils"},
    {"name": "HD TV", "icon": "tv"},
    {"name": "Washer & Dryer", "icon": "disc"},
    {"name": "Indoor Fireplace", "icon": "flame"},
    {"name": "Outdoor BBQ Grill", "icon": "utensils"},
    {"name": "Direct Beach Access", "icon": "umbrella"},
    {"name": "Panoramic Mountain View", "icon": "mountain"},
    {"name": "Pet Friendly", "icon": "paw-print"},
    {"name": "EV Car Charger", "icon": "zap"},
    {"name": "Private Balcony / Terrace", "icon": "sun"},
    {"name": "Keyless Self Check-in", "icon": "key"},
    {"name": "Gym & Fitness Equipment", "icon": "dumbbell"},
]

# 16 realistic listings across varied countries, property types, and price tiers
LISTINGS_DATA = [
    {
        "host_email": "sophie.dubois@airbnb-clone.local",
        "title": "Sunlit Artist Loft along Canal Saint-Martin",
        "description": "Exquisite high-ceiling Haussmannian loft featuring floor-to-ceiling French windows, curated vintage furnishings, bespoke espresso bar, and sweeping canal views. Walking distance to Le Marais galleries, boutique bistros, and République metro station.",
        "property_type": "Loft",
        "location": "Quai de Valmy, 10th Arrondissement",
        "city": "Paris",
        "country": "France",
        "latitude": 48.8712,
        "longitude": 2.3664,
        "price_per_night": 245.0,
        "cleaning_fee": 65.0,
        "service_fee": 0.14,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.5,
        "amenity_names": ["Fast Wifi", "Dedicated Workspace", "Chef Kitchen", "HD TV", "Keyless Self Check-in", "Air Conditioning"],
        "images": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Cliffside Mediterranean Villa with Infinity Terrace",
        "description": "Perched dramatically above the Tyrrhenian Sea, this whitewashed villa features an infinity dipping pool, bougainvillea-framed terraces, stone archways, and breathtaking sunsets over the Amalfi coastline. Direct private steps lead to pebble cove beach below.",
        "property_type": "Villa",
        "location": "Via Panoramica 42",
        "city": "Amalfi",
        "country": "Italy",
        "latitude": 40.6340,
        "longitude": 14.6027,
        "price_per_night": 580.0,
        "cleaning_fee": 120.0,
        "service_fee": 0.14,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "amenity_names": ["Fast Wifi", "Private Pool", "Direct Beach Access", "Private Balcony / Terrace", "Chef Kitchen", "Outdoor BBQ Grill"],
        "images": [
            "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "marcus.chen@airbnb-clone.local",
        "title": "Historic Machiya Townhouse with Zen Rock Garden",
        "description": "Restored 110-year-old traditional Kyoto machiya crafted from fragrant cypress and cedar wood. Features authentic tatami tea rooms, deep cedar soaking onsen tub, tranquil moss and stone inner courtyard, and modern Japanese underfloor heating.",
        "property_type": "House",
        "location": "Higashiyama Ward, Gion District",
        "city": "Kyoto",
        "country": "Japan",
        "latitude": 34.9949,
        "longitude": 135.7770,
        "price_per_night": 310.0,
        "cleaning_fee": 55.0,
        "service_fee": 0.14,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 4,
        "bathrooms": 1.5,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Air Conditioning", "Chef Kitchen", "Keyless Self Check-in", "Dedicated Workspace"],
        "images": [
            "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Ski-In Ski-Out Timber Chalet with Cedar Hot Tub",
        "description": "Nestled in Aspen's Red Mountain pines, this grand timber lodge offers vaulted exposed-beam ceilings, floor-to-ceiling riverstone fireplace, heated outdoor jacuzzi overlooking Snowmass slopes, ski boot warmers, and private sauna.",
        "property_type": "Chalet",
        "location": "Red Mountain Ridge Rd",
        "city": "Aspen",
        "country": "United States",
        "latitude": 39.1911,
        "longitude": -106.8175,
        "price_per_night": 795.0,
        "cleaning_fee": 150.0,
        "service_fee": 0.14,
        "max_guests": 8,
        "bedrooms": 4,
        "beds": 6,
        "bathrooms": 3.5,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Indoor Fireplace", "Panoramic Mountain View", "Free Parking", "EV Car Charger", "Chef Kitchen"],
        "images": [
            "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "marcus.chen@airbnb-clone.local",
        "title": "Handcrafted Bamboo Treehouse with Jungle Canopy Pool",
        "description": "An architectural marvel curved entirely from sustainable giant bamboo. Suspended over the Ayung River valley in Ubud, enjoy 360-degree views of tropical jungle canopy, private plunge pool, outdoor river stone shower, and morning yoga pavilion.",
        "property_type": "Treehouse",
        "location": "Jalan Raya Sayan, Ubud",
        "city": "Bali",
        "country": "Indonesia",
        "latitude": -8.5069,
        "longitude": 115.2625,
        "price_per_night": 220.0,
        "cleaning_fee": 40.0,
        "service_fee": 0.14,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "amenity_names": ["Fast Wifi", "Private Pool", "Private Balcony / Terrace", "Chef Kitchen", "Keyless Self Check-in"],
        "images": [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "sophie.dubois@airbnb-clone.local",
        "title": "Camps Bay Oceanfront Penthouse with Rooftop Deck",
        "description": "Sleek contemporary penthouse directly overlooking Camps Bay's white sand beach and the Twelve Apostles mountain peaks. Seamless glass doors open onto a wraparound terrace with gas braai grill and private cocktail splash pool.",
        "property_type": "Apartment",
        "location": "Victoria Road, Camps Bay",
        "city": "Cape Town",
        "country": "South Africa",
        "latitude": -33.9515,
        "longitude": 18.3778,
        "price_per_night": 360.0,
        "cleaning_fee": 75.0,
        "service_fee": 0.14,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "amenity_names": ["Fast Wifi", "Private Pool", "Direct Beach Access", "Outdoor BBQ Grill", "Private Balcony / Terrace", "Air Conditioning"],
        "images": [
            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Whitewashed Caldera Cave House with Private Plunge",
        "description": "Hand-carved into the volcanic cliffs of Oia, this authentic cave suite features curved whitewashed walls, a heated indoor/outdoor hydrotherapy plunge pool, and unobstructed front-row views of the world-famous Santorini sunset.",
        "property_type": "Villa",
        "location": "Nikolaou Nomikou, Oia",
        "city": "Santorini",
        "country": "Greece",
        "latitude": 36.4618,
        "longitude": 25.3753,
        "price_per_night": 490.0,
        "cleaning_fee": 85.0,
        "service_fee": 0.14,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.0,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Private Balcony / Terrace", "Air Conditioning", "Keyless Self Check-in"],
        "images": [
            "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "marcus.chen@airbnb-clone.local",
        "title": "Rustic Lakefront Cedar Cabin in Banff Wilderness",
        "description": "Authentic Canadian timber cabin on the quiet shores of Lake Minnewanka. Complete with handcrafted pine furnishings, wood-burning stone stove, private canoe dock, star-gazing veranda, and easy access to hiking trails and wildlife viewing.",
        "property_type": "Cabin",
        "location": "Lake Minnewanka Way",
        "city": "Banff",
        "country": "Canada",
        "latitude": 51.1784,
        "longitude": -115.5708,
        "price_per_night": 275.0,
        "cleaning_fee": 60.0,
        "service_fee": 0.14,
        "max_guests": 5,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 1.0,
        "amenity_names": ["Fast Wifi", "Indoor Fireplace", "Panoramic Mountain View", "Free Parking", "Pet Friendly", "Outdoor BBQ Grill"],
        "images": [
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "sophie.dubois@airbnb-clone.local",
        "title": "Boho-Chic Eco Sanctuary Villa with Cenote Pool",
        "description": "Tucked discreetly into the lush Tulum jungle, this open-concept sustainable villa blends raw concrete, warm tropical hardwoods, woven artisan textiles, and a private natural swimming cenote. Minutes by bicycle from the Caribbean beach clubs.",
        "property_type": "Villa",
        "location": "Aldea Zama Eco-Community",
        "city": "Tulum",
        "country": "Mexico",
        "latitude": 20.2114,
        "longitude": -87.4654,
        "price_per_night": 340.0,
        "cleaning_fee": 70.0,
        "service_fee": 0.14,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 3,
        "bathrooms": 2.5,
        "amenity_names": ["Fast Wifi", "Private Pool", "Air Conditioning", "Chef Kitchen", "Private Balcony / Terrace", "Free Parking"],
        "images": [
            "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Panoramic Lake & Alpine Penthouse in Enge",
        "description": "Ultra-modern Swiss architectural gem overlooking Lake Zurich and the distant Glarus Alps. Features minimalist oak flooring, smart home automation, expansive glass sky-lounge, and a tranquil spa bathroom with rain showers.",
        "property_type": "Apartment",
        "location": "Seestrasse 112, Enge",
        "city": "Zurich",
        "country": "Switzerland",
        "latitude": 47.3601,
        "longitude": 8.5342,
        "price_per_night": 460.0,
        "cleaning_fee": 90.0,
        "service_fee": 0.14,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "amenity_names": ["Fast Wifi", "Dedicated Workspace", "Panoramic Mountain View", "Chef Kitchen", "EV Car Charger", "Keyless Self Check-in"],
        "images": [
            "https://images.unsplash.com/photo-1502005229762-ae1b460020e2?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "marcus.chen@airbnb-clone.local",
        "title": "Oceanfront Tropical Sunset Bungalow on Kaanapali",
        "description": "Step directly from your mahogany lanai onto the warm sands of West Maui. Enjoy world-class whale watching from your living room, personal surfboards, outdoor tiki grill, lush orchid garden, and gentle trade wind breezes.",
        "property_type": "Beachfront",
        "location": "Lower Honoapiilani Rd, Lahaina",
        "city": "Maui",
        "country": "United States",
        "latitude": 20.9328,
        "longitude": -156.6852,
        "price_per_night": 520.0,
        "cleaning_fee": 110.0,
        "service_fee": 0.14,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2.0,
        "amenity_names": ["Fast Wifi", "Direct Beach Access", "Air Conditioning", "Free Parking", "Outdoor BBQ Grill", "Washer & Dryer"],
        "images": [
            "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "sophie.dubois@airbnb-clone.local",
        "title": "Glass Aurora Cabin with Private Geothermal Hot Tub",
        "description": "Gaze upon the dancing Northern Lights directly from your cozy wool-topped bed through heated panoramic glass ceilings. Located on Iceland's famous Golden Circle, includes natural geothermal hot spring tub, sauna, and total volcanic seclusion.",
        "property_type": "Cabin",
        "location": "Haukadalur Valley, Golden Circle",
        "city": "Reykjavik",
        "country": "Iceland",
        "latitude": 64.3104,
        "longitude": -20.3024,
        "price_per_night": 390.0,
        "cleaning_fee": 70.0,
        "service_fee": 0.14,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Free Parking", "Panoramic Mountain View", "Indoor Fireplace"],
        "images": [
            "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "marcus.chen@airbnb-clone.local",
        "title": "Gothic Quarter Rooftop Apartment with Citrus Terrace",
        "description": "Charming Catalan character meets modern Scandinavian comfort. Features original vaulted terracotta brick ceilings, wrought iron Juliet balconies, private citrus rooftop terrace overlooking Santa Maria del Mar, and designer kitchen.",
        "property_type": "Apartment",
        "location": "Carrer dels Banys Vells, El Born",
        "city": "Barcelona",
        "country": "Spain",
        "latitude": 41.3833,
        "longitude": 2.1818,
        "price_per_night": 175.0,
        "cleaning_fee": 45.0,
        "service_fee": 0.14,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.0,
        "amenity_names": ["Fast Wifi", "Air Conditioning", "Private Balcony / Terrace", "Chef Kitchen", "HD TV", "Keyless Self Check-in"],
        "images": [
            "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "sophie.dubois@airbnb-clone.local",
        "title": "Elegant Kensington Victorian Townhouse with Garden",
        "description": "Stately 3-story Victorian residence moments from Kensington Gardens and Hyde Park. Featuring original marble fireplaces, library sitting room, private walled English rose garden, AGA range cooker, and curated art collection.",
        "property_type": "House",
        "location": "Victoria Grove, Kensington",
        "city": "London",
        "country": "United Kingdom",
        "latitude": 51.4988,
        "longitude": -0.1915,
        "price_per_night": 410.0,
        "cleaning_fee": 95.0,
        "service_fee": 0.14,
        "max_guests": 5,
        "bedrooms": 3,
        "beds": 3,
        "bathrooms": 2.5,
        "amenity_names": ["Fast Wifi", "Dedicated Workspace", "Chef Kitchen", "Indoor Fireplace", "Washer & Dryer", "HD TV"],
        "images": [
            "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Lake Wakatipu Glass Sanctuary with Mountain Vistas",
        "description": "Architect-designed glass and schist stone pavilion cantilevering over Queenstown's crystal clear Lake Wakatipu. Features gas fire pit deck, sunken spa pool, wine cellar, and uninterrupted vistas of the Remarkables mountain range.",
        "property_type": "Villa",
        "location": "Frankton Road, Queenstown",
        "city": "Queenstown",
        "country": "New Zealand",
        "latitude": -45.0312,
        "longitude": 168.6626,
        "price_per_night": 550.0,
        "cleaning_fee": 115.0,
        "service_fee": 0.14,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Panoramic Mountain View", "Chef Kitchen", "Indoor Fireplace", "Free Parking", "EV Car Charger"],
        "images": [
            "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80",
        ],
    },
    {
        "host_email": "elena.rostova@airbnb-clone.local",
        "title": "Alpine Chalet with Direct Matterhorn Glacier View",
        "description": "Exclusive ski chalet positioned directly opposite the iconic pyramid of the Matterhorn. Hand-hewn Swiss stone pine interior, private outdoor hot tub on heated larch deck, wood-burning fireplace, and direct access to Gornergrat ski trails.",
        "property_type": "Chalet",
        "location": "Winkelmatten, Zermatt",
        "city": "Zermatt",
        "country": "Switzerland",
        "latitude": 45.9765,
        "longitude": 7.7491,
        "price_per_night": 680.0,
        "cleaning_fee": 130.0,
        "service_fee": 0.14,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 2.5,
        "amenity_names": ["Fast Wifi", "Hot Tub", "Indoor Fireplace", "Panoramic Mountain View", "Chef Kitchen", "Keyless Self Check-in"],
        "images": [
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        ],
    },
]

# Reviews connecting guest users with listings
REVIEWS_DATA = [
    {
        "listing_index": 0,  # Paris Loft
        "guest_email": "alex.morgan@airbnb-clone.local",
        "rating": 5,
        "comment": "An extraordinary apartment! The canal view in the morning with coffee was idyllic. Sophie was a wonderful host and provided amazing bakery recommendations.",
    },
    {
        "listing_index": 0,  # Paris Loft
        "guest_email": "maya.patel@airbnb-clone.local",
        "rating": 5,
        "comment": "The light in this loft is unreal. Spotlessly clean, high ceilings, very fast wifi for remote work, and located in one of Paris's coolest neighborhoods.",
    },
    {
        "listing_index": 1,  # Amalfi Villa
        "guest_email": "liam.oconnor@airbnb-clone.local",
        "rating": 5,
        "comment": "Words cannot describe the view from this terrace. Waking up to the sea and sunset wine by the pool made this the best vacation of our lives.",
    },
    {
        "listing_index": 2,  # Kyoto Machiya
        "guest_email": "alex.morgan@airbnb-clone.local",
        "rating": 5,
        "comment": "Staying in a real historical machiya with a zen courtyard was an unforgettable cultural experience. The soaking tub after walking Gion was heaven.",
    },
    {
        "listing_index": 3,  # Aspen Chalet
        "guest_email": "maya.patel@airbnb-clone.local",
        "rating": 5,
        "comment": "Skiing right up to the back door and hopping straight into the hot tub surrounded by snow was perfection. The stone fireplace was super cozy.",
    },
    {
        "listing_index": 4,  # Bali Treehouse
        "guest_email": "liam.oconnor@airbnb-clone.local",
        "rating": 5,
        "comment": "Pure magic in the jungle. The bamboo craftsmanship is breathtaking. Falling asleep to river sounds and waking up among the treetops was so peaceful.",
    },
    {
        "listing_index": 5,  # Cape Town Penthouse
        "guest_email": "alex.morgan@airbnb-clone.local",
        "rating": 5,
        "comment": "Unbelievable ocean views and sunsets over Camps Bay! Very modern, secure, and walking distance to all restaurants on the promenade.",
    },
    {
        "listing_index": 6,  # Santorini Cave
        "guest_email": "maya.patel@airbnb-clone.local",
        "rating": 5,
        "comment": "The private caldera plunge pool is worth every penny. You get the iconic sunset view without having to fight the crowds in Oia.",
    },
    {
        "listing_index": 7,  # Banff Cabin
        "guest_email": "liam.oconnor@airbnb-clone.local",
        "rating": 4,
        "comment": "Wonderful secluded getaway by Lake Minnewanka. Stargazing by the campfire was spectacular. Cozy and peaceful.",
    },
    {
        "listing_index": 8,  # Tulum Villa
        "guest_email": "alex.morgan@airbnb-clone.local",
        "rating": 5,
        "comment": "The private cenote plunge pool in the jungle was breathtaking. Amazing design, super comfortable beds, and very tranquil.",
    },
    {
        "listing_index": 9,  # Zurich Penthouse
        "guest_email": "maya.patel@airbnb-clone.local",
        "rating": 5,
        "comment": "Flawless Swiss design and pristine cleanliness. Panoramic view of Lake Zurich was stunning, and check-in was seamless.",
    },
    {
        "listing_index": 10, # Maui Bungalow
        "guest_email": "liam.oconnor@airbnb-clone.local",
        "rating": 5,
        "comment": "You cannot get closer to the ocean. We saw sea turtles right outside the lanai every afternoon. Will definitely be returning!",
    },
    {
        "listing_index": 11, # Iceland Aurora Cabin
        "guest_email": "alex.morgan@airbnb-clone.local",
        "rating": 5,
        "comment": "We saw the Northern Lights dancing right through the glass ceiling above our bed! An experience that took our breath away.",
    },
    {
        "listing_index": 12, # Barcelona Apartment
        "guest_email": "maya.patel@airbnb-clone.local",
        "rating": 4,
        "comment": "Super lively location in El Born. The private terrace with citrus trees was our favorite spot for tapas and sangria.",
    },
    {
        "listing_index": 13, # London Townhouse
        "guest_email": "liam.oconnor@airbnb-clone.local",
        "rating": 5,
        "comment": "A true Kensington treasure. Beautiful private garden, peaceful street, and classic British charm throughout.",
    },
]

# Sample realistic bookings (past and upcoming)
def get_sample_bookings(today: date = None):
    if today is None:
        today = date.today()
    return [
        {
            "listing_index": 0,  # Paris Loft
            "guest_email": "alex.morgan@airbnb-clone.local",
            "check_in": today - timedelta(days=20),
            "check_out": today - timedelta(days=15),
            "guests": 2,
            "status": "completed",
        },
        {
            "listing_index": 1,  # Amalfi Villa
            "guest_email": "liam.oconnor@airbnb-clone.local",
            "check_in": today - timedelta(days=12),
            "check_out": today - timedelta(days=7),
            "guests": 4,
            "status": "completed",
        },
        {
            "listing_index": 2,  # Kyoto Machiya
            "guest_email": "alex.morgan@airbnb-clone.local",
            "check_in": today + timedelta(days=10),
            "check_out": today + timedelta(days=15),
            "guests": 2,
            "status": "confirmed",
        },
        {
            "listing_index": 4,  # Bali Treehouse
            "guest_email": "maya.patel@airbnb-clone.local",
            "check_in": today + timedelta(days=25),
            "check_out": today + timedelta(days=30),
            "guests": 2,
            "status": "confirmed",
        },
        {
            "listing_index": 6,  # Santorini Cave
            "guest_email": "liam.oconnor@airbnb-clone.local",
            "check_in": today + timedelta(days=40),
            "check_out": today + timedelta(days=45),
            "guests": 2,
            "status": "confirmed",
        },
    ]

# Wishlist / Favorites mappings
FAVORITES_DATA = [
    {"guest_email": "alex.morgan@airbnb-clone.local", "listing_indexes": [1, 3, 6, 11]},
    {"guest_email": "liam.oconnor@airbnb-clone.local", "listing_indexes": [0, 4, 10, 14]},
    {"guest_email": "maya.patel@airbnb-clone.local", "listing_indexes": [2, 5, 8, 15]},
]
